# Generated by Django 5.1 on 2024-08-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
